FC=wfl386

all: mandel.exe show.exe tidy .SYMBOLIC

mandel.exe: mandel.obj period2d.obj pbmtools.obj ouchow.obj drawow.obj
	$(FC) period2d.obj pbmtools.obj ouchow.obj drawow.obj mandel.obj

show.exe: show.obj period2d.obj pbmtools.obj ouchow.obj drawow.obj
	$(FC) period2d.obj pbmtools.obj ouchow.obj drawow.obj show.obj

show.obj: show.f makefile
	$(FC) -c show.f

mandel.obj: mandel.f makefile
	$(FC) -c mandel.f

ouchow.obj: ouchow.f makefile
	$(FC) -c ouchow.f

drawow.obj: drawow.f makefile
	$(FC) -c drawow.f

period2d.obj: period2d.f makefile
	$(FC) -c period2d.f

pbmtools.obj: pbmtools.f makefile
	$(FC) -c pbmtools.f


clean: .SYMBOLIC
	del *.obj
	del *.exe
	del *.err
	del out.pbm

tidy: .SYMBOLIC
	del *.obj
	del *.err

